# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('edit_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('abn_number', models.CharField(max_length=40)),
                ('is_individual', models.CharField(max_length=40)),
                ('address_street', models.CharField(max_length=60)),
                ('address_city', models.CharField(max_length=60)),
                ('address_state', models.CharField(max_length=25)),
                ('address_postcode', models.CharField(max_length=10)),
                ('address_country', models.CharField(max_length=25)),
                ('fax_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=60)),
                ('billing_address', models.CharField(max_length=250)),
                ('badges', models.CharField(max_length=250)),
                ('tax_rate_uuid', models.CharField(max_length=38)),
                ('parent_company_uuid', models.CharField(default='', max_length=38)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Contact',
            fields=[
                ('uuid', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('edit_date', models.DateTimeField()),
                ('first', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=16)),
                ('mobile', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('contact_type', models.CharField(max_length=60)),
                ('is_primary_contact', models.CharField(max_length=38)),
                ('company_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.Company')),
            ],
        ),
    ]
